### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by rakekniven**
Fix for #64

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by rakekniven** [comment]
@MariusBluem I am allowed to merge this PR. Is it a common use to merge my own PR's? Or should this be done by third person?

**Comment by MariusBluem** [comment]
Merged. Thanks for your contribution :)

**Comment by rakekniven** [comment]
@MariusBluem Would be great if you could answer my question above. Like to know such things :-)

**Comment by MariusBluem** [comment]
@rakekniven Submit commit, 2 reviews from other contributors and members of the project, merge (whoever has the right to do - even if you did the PR by yourself) - for core/server-contributions.

For apps (like calendar or password_policy) only a single review is needed by another contributor and member of the Nextcloud project. You could merge if you want.

However: There is no time-pressure. If you are unsure about merging - just wait - somebody of the Nextcloud project will take care of it, especially before a release we have a look over all pending PRs and triage what to merge :)

**Comment by rakekniven** [comment]
Hey @MariusBluem Thanks for explanation. I am patient, tell translators at Transifex to be patient when source strings errors are reported and they are not fixed within few days :-)

**Comment by MariusBluem** [comment]
@rakekniven Well, in this case over here I think nobody can complain about the long time needed to merge 😝😝

If there is no reason (we would explain) you can be sure that PRs just fixing typos or language issues are merged within not longer than a week.

**Comment by rakekniven** [comment]
As written I am patient and happy how the community works. All my PRs have been merged. It's more like. I found something, on Transifex I can immediately fix it for my languages so why can the source string issue not being fixed right now as well ;-) @MariusBluem

**Pull request merged**
