### PR TITLE
fix: Move from private `OC\HintException` to public `OCP\HintException`

### PR DESCRIPTION
**Pull request by susnux**
We should not use private API in apps, especially if there is a public alternative.

### CODE REVIEW

**Review by nickvergessen — COMMENTED** [review]
This breaks all the consumers of the API, because OCP does not extend the former exception, so any catch does not work anymore?🤔

**Comment by susnux** [comment]
> This breaks all the consumers of the API, because OCP does not extend the former exception, so any catch does not work anymore?🤔

No basically we can use OCP because users of the API that still throw the OC exception will still work -> OC extends OCP meaning as we catch OCP we also catch OC.
Thus we still catch all exceptions.

<del>Quick search did not show any API users, but you are right if that API is expected to be used by external apps, then this breaks. Still I think, especially if this is used externally, we should not enforce API users to use private Nextcloud API.
So lets only change the documentation so that users catch `OCP\HintException` as OC extends from OCP, meaning catching OCP works even when throwing OC. (The OC exception is deprecated since NC23).</del>

**Comment by nickvergessen** [comment]
> Still I think, especially if this is used externally, we should not enforce API users to use private Nextcloud API.
So lets only change the documentation so that users catch OCP\HintException as OC extends from OCP, meaning catching OCP works even when throwing OC. (The OC exception is deprecated since NC23).

This part is exactly the right one.

You don't find any consumers of the API because you look for the wrong one.
Apps emit `OCP\Security\Events\ValidatePasswordPolicyEvent` which is listened to by this app in https://github.com/nextcloud/password_policy/blob/master/lib/Listener/ValidatePasswordPolicyEventListener.php

https://github.com/search?q=org%3Anextcloud%20ValidatePasswordPolicyEvent&type=code

Used in our org in 4 repos at least:
- Talk
- Guests
- Server:
    - Sharing
    - User backend
- user_sql

So the correct way would be to document it in the dev docs that OCP should be catched now and then we can switch to it in some releases

**Comment by susnux** [comment]
As @nickvergessen mentioned we can not replace this directly but need to deprecate first.

**Comment by susnux** [comment]
I checked all using apps in our organization, all migrated to `OCP\HintException` (or do not catch the exception at all).
(Maybe because that exception was not documented?).

So I think we should be good for the Nextcloud 31 cycle.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
