### PR TITLE
Update list of common passwords

### PR DESCRIPTION
**Pull request by kesselb**
Source: https://github.com/danielmiessler/SecLists/blob/master/Passwords/xato-net-10-million-passwords-1000000.txt

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Is this just an update from the same source as the original list or a new source?

**Comment by kesselb** [comment]
> Is this just an update from the same source as the original list or a new source?

I think so :see_no_evil: Guessed the list name from the readme.md ;)

> By default the app enforces a minimum password length of 10 characters and checks every password against the **1.000.000** most common passwords.

README.md 

> The password lists are from https://github.com/danielmiessler/SecLists/tree/master/Passwords, they are converted in a PHP array using the "converter.php" script.

README.md next to converter.php

**Comment by ChristophWurst** [comment]
But let's wait for @rullzer's final :+1:

**Comment by muhammadalik** [comment]
//github.com/danielmiessler/SecLists/blob/master/Passwords/xato-net-10-million-passwords-1000000.txt

**Pull request merged**
