### PR TITLE
[stable23] Update some libs

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by PVince81** [comment]
recompiling locally

**Comment by blizzz** [comment]
some ci is failing, i assume pgsql is unrelated.

**Comment by PVince81** [comment]
lock file issues possibly

**Comment by PVince81** [comment]
recompiled with node v14

**Comment by blizzz** [comment]
postgresql failures probably because it goes against 15, not relevant here.

**Pull request merged**
