### PR TITLE
Added app icon from core/action password.svg

### PR DESCRIPTION
**Pull request by eppfel**
As disccussed in nextcloud/server#856
@nextcloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
CI failure unrelated

**Comment by MorrisJobke** [comment]
stable10 31e67ef
stable9 5835cbd

**Comment by jancborchardt** [comment]
Yo @eppfel are you going to be at our Nextcloud conference in Berlin as well? https://conf.nextcloud.com/ :) There’s travel/hotel cost support for contributors.

**Pull request merged**
