### PR TITLE
Use typed events

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Requires https://github.com/nextcloud/server/pull/18019

### CODE REVIEW

**Comment by rullzer** [comment]
Can't we keep both events for now?

**Comment by ChristophWurst** [comment]
> Can't we keep both events for now?

Yes, but the old one uses the GenericEvent. Once that gets removed it will do :boom:

**Comment by rullzer** [comment]
> > Can't we keep both events for now?
> 
> Yes, but the old one uses the GenericEvent. Once that gets removed it will do boom

Sure but it won't just be removed right. That will opnly happen with a symfony upgrade? for 18 it should just work or?

**Comment by ChristophWurst** [comment]
Done

**Pull request merged**
